title: ML Outtakes
description: Anecdotes on how statistics, ML, and AI sausages are made.
url: https://ml-outtakes.github.io/
exclude:
  - .git
  - venv
  - vendor
  - Gemfile
  - Gemfile.lock
collections:
  articles:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
